#pragma once

#include "NativeGameplayTags.h"

namespace HOGGameplayTags
{
	//Team (아군적군 구분하는태그)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Player)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Object)

	//입력
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)


	//Ability 입력
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Primary)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Defense)

	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill1)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill2)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill3)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill4)
	
	//State
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit)
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking)
	
	//Enemy Ability
	HOGWARTSLEGACYCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack)
	
}
